### ISSUE TITLE
Array Index out of bound for Android

### ISSUE THREAD

**Issue by AmbujMishra** [AmbujMishra/Gbits#11]
01-03 16:52:51.395: I/AndroidInput(9631): sensor listener setup
01-03 16:52:51.445: W/GL2JNIView(9631): creating OpenGL ES 2.0 context
01-03 16:52:51.465: I/GL2(9631): all initialized 2
01-03 16:52:51.465: I/AndroidGraphics(9631): OGL renderer: Mali-400 MP
01-03 16:52:51.465: I/AndroidGraphics(9631): OGL vendor: ARM
01-03 16:52:51.465: I/AndroidGraphics(9631): OGL version: OpenGL ES 2.0
01-03 16:52:51.465: I/AndroidGraphics(9631): OGL extensions: GL_OES_texture_npot GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_depth24 GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth_texture GL_OES_packed_depth_stencil GL_EXT_texture_format_BGRA8888 GL_EXT_blend_minmax GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_rgb8_rgba8 GL_EXT_multisampled_render_to_texture GL_EXT_discard_framebuffer 
01-03 16:52:51.465: I/AndroidGraphics(9631): framebuffer: (5, 6, 5, 0)
01-03 16:52:51.465: I/AndroidGraphics(9631): depthbuffer: (24)
01-03 16:52:51.465: I/AndroidGraphics(9631): stencilbuffer: (8)
01-03 16:52:51.465: I/AndroidGraphics(9631): samples: (0)
01-03 16:52:51.465: I/AndroidGraphics(9631): coverage sampling: (false)
01-03 16:52:51.475: I/AndroidGraphics(9631): Managed meshes/app: { }
01-03 16:52:51.475: I/AndroidGraphics(9631): Managed textures/app: { }
01-03 16:52:51.475: I/AndroidGraphics(9631): Managed shaders/app: { }
01-03 16:52:51.475: I/AndroidGraphics(9631): Managed buffers/app: { }
01-03 16:52:52.656: I/System.out(9631): input screen
01-03 16:52:52.666: I/System.out(9631): input screen
01-03 16:52:52.666: I/System.out(9631): animation screen show method
01-03 16:52:52.666: I/System.out(9631): down animation
01-03 16:52:52.676: I/FPSLogger(9631): fps: 2
01-03 16:52:52.676: I/System.out(9631): down animation
...
01-03 16:52:52.857: I/System.out(9631): down animation
01-03 16:52:52.867: I/System.out(9631): down animation
01-03 16:52:52.877: I/System.out(9631): input screen
01-03 16:52:52.887: I/System.out(9631): input screen
01-03 16:52:52.907: I/System.out(9631): input screen
.....
01-03 16:52:54.588: I/System.out(9631): input screen
01-03 16:52:54.598: I/System.out(9631): animation screen show method
01-03 16:52:54.618: I/System.out(9631): left animation
...
01-03 16:52:56.630: I/System.out(9631): input screen
01-03 16:52:56.650: I/System.out(9631): input screen
01-03 16:52:56.670: I/System.out(9631): input screen
01-03 16:52:56.690: I/System.out(9631): input screen
01-03 16:52:56.710: I/System.out(9631): animation screen show method
01-03 16:52:56.710: I/FPSLogger(9631): fps: 59
01-03 16:52:56.720: I/System.out(9631): right animation
01-03 16:52:56.760: W/dalvikvm(9631): threadid=11: thread exiting with uncaught exception (group=0x40aab210)
01-03 16:52:56.770: E/AndroidRuntime(9631): FATAL EXCEPTION: GLThread 456
01-03 16:52:56.770: E/AndroidRuntime(9631): java.lang.StringIndexOutOfBoundsException: length=2; regionStart=-1; regionLength=2
01-03 16:52:56.770: E/AndroidRuntime(9631):     at java.lang.String.startEndAndLength(String.java:593)
01-03 16:52:56.770: E/AndroidRuntime(9631):     at java.lang.String.substring(String.java:1474)
01-03 16:52:56.770: E/AndroidRuntime(9631):     at com.Gbits.Screens.AnimaScreen.render(AnimaScreen.java:273)
01-03 16:52:56.770: E/AndroidRuntime(9631):     at com.badlogic.gdx.Game.render(Game.java:46)
01-03 16:52:56.770: E/AndroidRuntime(9631):     at com.Gbits.Screens.GbitsGame.render(GbitsGame.java:86)
01-03 16:52:56.770: E/AndroidRuntime(9631):     at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:416)
01-03 16:52:56.770: E/AndroidRuntime(9631):     at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1462)
01-03 16:52:56.770: E/AndroidRuntime(9631):     at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1216)
01-03 16:54:00.813: I/AndroidInput(9727): sensor listener setup
01-03 16:54:00.823: I/AndroidInput(9727): sensor listener tear down
01-03 16:54:05.638: I/AndroidInput(9727): sensor listener setup
01-03 16:54:05.638: W/GL2JNIView(9727): creating OpenGL ES 2.0 context
01-03 16:54:05.688: I/GL2(9727): all initialized 2
01-03 16:54:05.688: I/AndroidGraphics(9727): OGL renderer: Mali-400 MP
01-03 16:54:05.688: I/AndroidGraphics(9727): OGL vendor: ARM
01-03 16:54:05.688: I/AndroidGraphics(9727): OGL version: OpenGL ES 2.0
01-03 16:54:05.688: I/AndroidGraphics(9727): OGL extensions: GL_OES_texture_npot GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_depth24 GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth_texture GL_OES_packed_depth_stencil GL_EXT_texture_format_BGRA8888 GL_EXT_blend_minmax GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_rgb8_rgba8 GL_EXT_multisampled_render_to_texture GL_EXT_discard_framebuffer 
01-03 16:54:05.688: I/AndroidGraphics(9727): framebuffer: (5, 6, 5, 0)
01-03 16:54:05.698: I/AndroidGraphics(9727): depthbuffer: (24)
01-03 16:54:05.698: I/AndroidGraphics(9727): stencilbuffer: (8)
01-03 16:54:05.698: I/AndroidGraphics(9727): samples: (0)
01-03 16:54:05.698: I/AndroidGraphics(9727): coverage sampling: (false)
01-03 16:54:05.698: I/AndroidGraphics(9727): Managed meshes/app: { }
01-03 16:54:05.698: I/AndroidGraphics(9727): Managed textures/app: { }
01-03 16:54:05.708: I/AndroidGraphics(9727): Managed shaders/app: { }
01-03 16:54:05.708: I/AndroidGraphics(9727): Managed buffers/app: { }
01-03 16:54:05.908: I/AndroidGraphics(9727): resumed
01-03 16:54:09.191: I/FPSLogger(9727): fps: 0
01-03 16:56:42.611: I/System.out(10069): input screen
01-03 16:56:42.631: I/System.out(10069): input screen
01-03 16:56:42.641: I/System.out(10069): animation screen show method
01-03 16:56:42.661: I/System.out(10069): down animation
01-03 16:56:42.691: W/dalvikvm(10069): threadid=11: thread exiting with uncaught exception (group=0x40aab210)
01-03 16:56:42.701: E/AndroidRuntime(10069): FATAL EXCEPTION: GLThread 495
01-03 16:56:42.701: E/AndroidRuntime(10069): java.lang.StringIndexOutOfBoundsException: length=4; regionStart=3; regionLength=2
01-03 16:56:42.701: E/AndroidRuntime(10069):    at java.lang.String.startEndAndLength(String.java:593)
01-03 16:56:42.701: E/AndroidRuntime(10069):    at java.lang.String.substring(String.java:1474)
01-03 16:56:42.701: E/AndroidRuntime(10069):    at com.Gbits.Screens.AnimaScreen.render(AnimaScreen.java:416)
01-03 16:56:42.701: E/AndroidRuntime(10069):    at com.badlogic.gdx.Game.render(Game.java:46)
01-03 16:56:42.701: E/AndroidRuntime(10069):    at com.Gbits.Screens.GbitsGame.render(GbitsGame.java:86)
01-03 16:56:42.701: E/AndroidRuntime(10069):    at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:416)
01-03 16:56:42.701: E/AndroidRuntime(10069):    at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1462)
01-03 16:56:42.701: E/AndroidRuntime(10069):    at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1216)
#01-03 16:56:44.603: I/Process(10069): Sending signal. PID: 10069 SIG: 9

01-03 17:02:16.817: I/System.out(10534): input screen
01-03 17:02:16.837: I/System.out(10534): animation screen show method
01-03 17:02:16.847: I/System.out(10534): right animation
01-03 17:02:16.887: W/dalvikvm(10534): threadid=12: thread exiting with uncaught exception (group=0x40aab210)
01-03 17:02:16.897: E/AndroidRuntime(10534): FATAL EXCEPTION: GLThread 541
01-03 17:02:16.897: E/AndroidRuntime(10534): java.lang.StringIndexOutOfBoundsException: length=4; regionStart=-1; regionLength=2
01-03 17:02:16.897: E/AndroidRuntime(10534):    at java.lang.String.startEndAndLength(String.java:593)
01-03 17:02:16.897: E/AndroidRuntime(10534):    at java.lang.String.substring(String.java:1474)
01-03 17:02:16.897: E/AndroidRuntime(10534):    at com.Gbits.Screens.AnimaScreen.render(AnimaScreen.java:273)
01-03 17:02:16.897: E/AndroidRuntime(10534):    at com.badlogic.gdx.Game.render(Game.java:46)
01-03 17:02:16.897: E/AndroidRuntime(10534):    at com.Gbits.Screens.GbitsGame.render(GbitsGame.java:86)
01-03 17:02:16.897: E/AndroidRuntime(10534):    at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:416)
01-03 17:02:16.897: E/AndroidRuntime(10534):    at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1462)
01-03 17:02:16.897: E/AndroidRuntime(10534):    at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1216)

**Comment by AmbujMishra** [comment]
Fixed.Use AnimaScreen2. Test and close the ticket.
