### ISSUE TITLE
Check Android touch exception

### ISSUE THREAD

**Issue by AmbujMishra** [AmbujMishra/Gbits#17]
01-07 00:27:46.087: E/AndroidRuntime(31292): FATAL EXCEPTION: GLThread 4279
01-07 00:27:46.087: E/AndroidRuntime(31292): java.lang.StringIndexOutOfBoundsException: length=3; regionStart=2; regionLength=2
01-07 00:27:46.087: E/AndroidRuntime(31292):    at java.lang.String.startEndAndLength(String.java:593)
01-07 00:27:46.087: E/AndroidRuntime(31292):    at java.lang.String.substring(String.java:1474)
01-07 00:27:46.087: E/AndroidRuntime(31292):    at com.Gbits.Screens.AnimaScreen.render(AnimaScreen.java:414)
01-07 00:27:46.087: E/AndroidRuntime(31292):    at com.badlogic.gdx.Game.render(Game.java:46)
01-07 00:27:46.087: E/AndroidRuntime(31292):    at com.Gbits.Screens.GbitsGame.render(GbitsGame.java:90)
01-07 00:27:46.087: E/AndroidRuntime(31292):    at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:416)
01-07 00:27:46.087: E/AndroidRuntime(31292):    at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1462)
01-07 00:27:46.087: E/AndroidRuntime(31292):    at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1216)
01-07 00:27:46.127: D/dalvikvm(31292): GC_CONCURRENT freed 1638K, 16% free 9576K/11363K, paused 3ms+3ms
01-07 00:27:50.151: E/AndroidGraphics(31292): waiting for pause synchronization took too long; assuming deadlock and killing
01-07 00:27:50.151: I/Process(31292): Sending signal. PID: 31292 SIG: 9

**Comment by AmbujMishra** [comment]
Use AnimaScreen2. Test and close.

**Comment by AmbujMishra** [comment]
fixed..
