### ISSUE TITLE
Troubleshoot Below Android Eception

### ISSUE THREAD

**Issue by AmbujMishra** [AmbujMishra/Gbits#22]
01-24 13:00:13.147: E/AndroidRuntime(20362): FATAL EXCEPTION: GLThread 766
01-24 13:00:13.147: E/AndroidRuntime(20362): java.lang.StringIndexOutOfBoundsException: length=3; index=3
01-24 13:00:13.147: E/AndroidRuntime(20362):    at com.Gbits.Screens.BitContainer.getBit(BitContainer.java:168)
01-24 13:00:13.147: E/AndroidRuntime(20362):    at com.Gbits.Screens.AnimaScreen.render(AnimaScreen.java:123)
01-24 13:00:13.147: E/AndroidRuntime(20362):    at com.badlogic.gdx.Game.render(Game.java:46)

You are deleting character 2 somewhere in bit array.

**Comment by AmbujMishra** [comment]
This comes when some threads remains open for previous screen and you try to update bitcontainer. Currently couldn't reproduce it. So closing it for now.
